idf_component_register(
    SRCS "cansat_project.cpp"
         "rtos/tasks.cpp"
         "lsm9ds1/lsm9ds1_hal.c"
         "lsm9ds1/lsm9ds1_reg.c"
         "dps310/dps310.c"
         "i2c/i2c_bus.c"
         "fs/fs_handler.c"
         "rtos/rfm95_task.cpp"
         "servos/servos.c"
         "camera/anaglyph_core.cpp"
         "../lib/PTC06/ptc06.c"
    INCLUDE_DIRS "."
                 "rtos"
                 "lsm9ds1"
                 "dps310"
                 "servos"
                 "camera"
                 "EspHal"
                 "i2c"
                 "fs"
                 "../lib/PTC06"
                 "../lib/jpge"
)

spiffs_create_partition_image(storage ../data FLASH_IN_PROJECT)